### ISSUE TITLE
Why is it called SEMap?

### ISSUE THREAD

**Issue by sgraf812** [simonpj/triemap-paper#3]
This is a question that a student asked in review. I agree that it's non-obvious. I think it is short for "singleton and empty map", but I could only tell so after looking at the definition in the code, which is led by a banner that says as much.

**Comment by simonpj** [comment]
> I think it is short for "singleton and empty map"

Yes, that's right.  I'm entirely open to a better name.  But if we keep it we should add a footnote to explain it.
