### ISSUE TITLE
Matching SEMap

### ISSUE THREAD

**Issue by sgraf812** [simonpj/triemap-paper#7]
One of the open TODOs we had was that the matching `MExprMapX` implementation couldn't re-use the leaf-compressing `SEMap` implementation. I spent some time today prototyping one approach of making `SEMap` match-aware and subclassing our `TrieMap` class to a matching `MTrieMap` class with one crucial operation `lookupMTM :: TrieKey tm -> PatSubst Expr -> tm v -> Bag (PatSubst Expr, v)`. I think having an issue thread for this perhaps makes for a better presentation than via mail, so here it goes.

To recap where we left off, our (non-matching) `ExprMap'` looks like

```hs
data SEMap tm v
  = EmptySEM
  | SingleSEM (TrieKey tm) v
  | MultiSEM  (tm v)

type ExprMap = SEMap ExprMap'

data ExprMap' a
  = EM { em_bvar :: BoundVarMap a 
       , em_fvar :: FreeVarMap a

       , em_app  :: ExprMap (ExprMap a) -- NB: ExprMap, without '!
       , em_lit  :: Map.Map Lit a
       , em_lam  :: ExprMap a -- NB: ExprMap, without '!
       }
```

using `SEMap` in recursive positions. Nice! We got to reuse `SingleSEM`'s favorable memory footprint and don't need to write `EmptySEM`.

By contrast, `MExprMapX` looks like

```hs
data MExprMapX a
  = EmptyMEM
  | MEM { mem_tvar   :: Maybe a          -- First occurrence of a template tyvar
        , mem_xvar   :: PatOccs a       -- Subsequent occurrence of a template tyvar

        , mem_bvar   :: BoundVarMap a    -- Occurrence of a lam-bound tyvar
        , mem_fvar   :: FreeVarMap a     -- Occurrence of a completely free tyvar

        , mem_fun    :: MExprMapX (MExprMapX a) -- NB: Direct recursion back into MExprMapX
        , mem_tycon  :: Map.Map Lit a
        , mem_lam    :: MExprMapX a
        }
```

Why can't we re-use `SEMap` here? Because then how would you write the equivalent of `lkT :: DeBruijn Expr -> PatSubst Expr -> MExprMapX a -> Bag (PatSubst Expr, a)` for `SEMap`? Let's call this equivalent `lookupMSEM`:

```hs
lookupMSEM :: TrieMap tm => TrieKey tm -> PatSubst Expr -> SEMap tm v -> Bag (PatSubst Expr, v)
lookupMSEM !_ subst EmptySEM = Bag.empty
lookupMSEM tk subst (SingleSEM pk v) = ??? match tk against pk how ???
lookupMSEM tk subst (MultiSEM tm) = _ -- pretty easy: recurse once we have the type class
```

In the non-matching lookup impl, we simply inserted a check `tk == pk`. But we need not only equality here, we need *matching*.
What does it mean to match `tk` against `pk`?

One very simple impl would literally be to not care about pattern variables:

```hs
lookupMSEM tk subst (SingleSEM pk v) = if tk == pk then Just (subst, v) else Nothing
```

But that is quite dumb; we won't be able to use `SingleSEM` as soon as there is just a single `PatVar` in what is supposed to end up in `pk`. Hence I went on to designate a single constant `wildcardVar :: Var` as standing in for a pattern var occurrence. Now I can basically copy `eqDBExpr` and write

```hs
-- | The only 'Var' that is considered a template 'Var' in 'matchDBExpr'.
wildcardVar :: Var
wildcardVar = "*"

-- | First target expr, then pattern expr (which may contain wildcards as
-- template vars, but no non-linear PatVar occurrences)
matchDBExpr :: DeBruijn Expr -> DeBruijn Expr -> PatSubst Expr -> Maybe (PatSubst Expr)
matchDBExpr (D env1 e1) (D env2 (Var tv2)) subst
  | tv2 == wildcardVar
  = Just (extendPatSubst e1 subst)
matchDBExpr (D env1 (App s1 t1)) (D env2 (App s2 t2)) subst
  = matchDBExpr (D env1 s1) (D env2 s2) subst >>=
    matchDBExpr (D env1 t1) (D env2 t2)

matchDBExpr (D env1 (Var tv1)) (D env2 (Var tv2)) subst
  = case (lookupDBE tv1 env1, lookupDBE tv2 env2) of
      (Just bvi1, Just bvi2) | bvi1 == bvi2 -> Just subst
      (Nothing,   Nothing)                  -> Just subst
      _                                     -> Nothing

matchDBExpr (D _ (Lit tc1)) (D _ (Lit tc2)) subst
  | tc1 == tc2
  = Just subst

matchDBExpr (D env1 (Lam tv1 t1)) (D env2 (Lam tv2 t2)) subst
  = matchDBExpr (D (extendDBE tv1 env1) t1)
                (D (extendDBE tv2 env2) t2)
                subst

matchDBExpr _ _ _ = Nothing
```

And now we can have `Expr` stand for single-element `MExprMapX`s as long as there are no non-linear pattern var occs! It's a huge hack though and only works because we know how `Expr`s are formed.

Regardless, with this function, we can write

```hs
class MatchingKey k where
  matchKey :: k -> k -> PatSubst Expr -> Maybe (PatSubst Expr)

instance MatchingKey (DeBruijn Expr) where
  matchKey = matchDBExpr

-- New constraint here:    vvvvvvvvvvvvvvvvvvvvvvvv
lookupMSEM :: (TrieMap tm, MatchingKey (TrieKey tm)) => TrieKey tm -> PatSubst Expr -> SEMap tm v -> Bag (PatSubst Expr, v)
...
lookupMSEM tk subst (SingleSEM pk v) = Bag.fromMaybe $ flip (,) v <$> matchKey tk pk subst
...
```

And now we can finally have a subclass of `TrieMap`, `MTrieMap`, with matching implementations:

```hs
class TrieMap tm => MTrieMap tm where
  lookupMTM :: TrieKey tm -> PatSubst Expr -> tm v -> Bag (PatSubst Expr, v)

instance (MTrieMap tm, MatchingKey (TrieKey tm)) => MTrieMap (SEMap tm) where
  lookupMTM = lookupMSEM

instance (MTrieMap tm, MatchingKey [TrieKey tm]) => MTrieMap (ListMap' tm) where
  lookupMTM = _ -- elided
```

Which finally enables us to re-use `SEMap` in `MExprMap'`!

```hs
type MExprMapN = SEMap MExprMap'

data MExprMap' a
  = MEM' { mem'_tvar   :: Maybe a          -- First occurrence of a template tyvar
         , mem'_xvar   :: PatOccs a       -- Subsequent occurrence of a template tyvar

         , mem'_bvar   :: BoundVarMap a    -- Occurrence of a lam-bound tyvar
         , mem'_fvar   :: FreeVarMap a     -- Occurrence of a completely free tyvar

         , mem'_fun    :: MExprMapN (MExprMapN a)  -- NB: Without ', so recurses into SEMap
         , mem'_tycon  :: Map.Map Lit a
         , mem'_lam    :: MExprMapN a
         }

instance MTrieMap MExprMap' where
  lookupMTM = lookupMExprM

lookupMExprM :: DeBruijn Expr -> PatSubst Expr -> MExprMap' a -> Bag (PatSubst Expr, a)
lookupMExprM (D dbe ty) psubst (MEM' { .. })
  = ... lot of stuff ...
  where
    ...
    -- this one is perhaps the most interesting because it recurses into `lookupMTM`:
    go (App t1 t2) = Bag.concatMap (uncurry (lookupMTM (D dbe t2))) $
                      lookupMTM (D dbe t1) psubst mem'_fun
    ...
```

Nice! Note how the recursive structure is basically the same as with non-matching `lookupExprMap`.

# Conclusion

Now that we can reuse `SEMap` for the purpose of matching, we can again talk about deriving matching lookup `lookupMTM` truly polytypically. Previously we gave `MExprMap'` and said "this one works for `Expr`", but it lacked the cool higher-orderness of `SEMap` and `ListMap`.

I think one way to improve the value of the paper would be to really give the derivation function for `lookupMTM`, for arbitrary data types that sprinkle in some specific markers, like one saying "This constructor introduces a lambda binder" or "This constructor is for the occurrence of a pattern variable". I imagine some data-types-à-la-carte approach could work. But that would be a lot of work. What do you think?

**Comment by simonpj** [comment]
> One very simple impl would literally be to not care about pattern variables .. but this is a huge hack.

Would another be to require a class method for it?
```
-- Abstract PatSubst over v
data PatSubst v = TS { ts_subst :: IntMap.IntMap v
                     , ts_next  :: PatKey }

-- Not Expr, but (TrieKey tm)
lookupMSEM :: TrieMapM tm => TrieKey tm -> PatSubst (TrieKey tm)
           -> SEMap tm v -> Bag (PatSubst (TrieKey tm), v)
...
lookupMSEM tk subst (SingleSEM pk v)
  = case matches tk subst pk of
      Just subst' -> Just (subst, v)
      Nothing     -> Nothing
```
where `matches` is a method of the new TrieMapM class.

Maybe that is what you are doing in the latter part of your post, but I got lost.

By all means let's dicuss.  I'm quite keen not to drop this paper, and I'd be delighted if you carried it forward.
