### ISSUE TITLE
Define `view :: PatVars -> DeBruijnEnv  -> PatKeys -> Expr -> CExpr` and use it

### ISSUE THREAD

**Issue by sgraf812** [simonpj/triemap-paper#9]
In [Simon's talk](https://youtu.be/cT8G6FS2v94?t=2515), he says that we actually build the trie for a variant of the original `Expr` type, dubbed `Expr'`, that is properly de bruijinised and its pat vars canonicalised:

```hs
data Expr
  = Var Var
  | App Expr Expr
  | Lam Var Expr

data Expr'
  = BVar Int
  | FVar Var
  | PVar Int
  | App Expr' Expr'
  | Lam Expr'
```

Then *every* function that operates on the `Expr'` view takes an `Expr` and does the view in an ad-hoc fashion. I propose instead to extract the implicit `view` function. But we need to be a bit more careful to make it non-recursive, so that all the overhead will inline. We need to redefine `Expr'`, thus

```hs
data C a = C DeBruijnEnv PatKeys a
data Expr'
  = BVar Int
  | FVar Var
  | PVar Int
  | App' Expr Expr -- NB: Expr, not Expr'! so non-recursive
  | Lam' Expr
```

`C Expr` is quite similar to `DeBruijn Expr`, but it also stores the current `PatKeys`. We can define the following `view` function:

```hs
view :: PatVars -> C Expr -> C Expr'
view pvs (C env pks (Var v))
  | Just bv <- lookupDBE v env = C env pks (BVar bv)
  | v `Set.member` PatVars
  , (pks', pv) <- canonPV = C env pks' (PVar pv)
  | otherwise = C env pks (FVar v)
view pvs (C env pks (Lam v e)) = C (extendDBE v env) pks (Lam' e)
view pvs (C env pks (App f a)) = C env pks (App' f a)
```

And now call sites can simply match on `BVar`/`FVar`/`PVar` instead of doing the repeated lookups. `view` can be inlined and `Expr'` will cancel away with the surrounding pattern match.

This is all reminiscent of recursion schemes, where the formulation of a fold over a recursive data structure in terms of its non-recursive (but parameterised) signature functor leads to programs that we can optimise easily.

**Comment by goldfirere** [comment]
Sounds reasonable to me, but I can't say I feel confident I know the implications.

**Comment by sgraf812** [comment]
Simon really didn't want to define another (potentially huge) datatype, so he suggested the following view instead:

  ```hs
  viewOcc :: Var -> BoundVarEnv -> PatVarEnv -> Occ
  data Occ
      = BVar Int
      | FVar Var
      | PVar Int
  ```

And that works quite well for matching lookup. We simply keep around a `BoundVarEnv` and a `PatVarEnv` when we look at `Expr` to `viewOcc`s when we need to.

Unfortunately, at the moment I'm having a stab at unifying lookup where this approach seems to break apart. Thus I advocate for `Expr'` from the OP and counter the duplication issue with a Trees That Grow approach (this is the TLDR).

Consider the unification map `u = UniMap.fromList [∀{a,b}. T (T a b) Int :-> e1, ∀{c,d}. T (T c d) Bool :-> e2]`. Note that both patterns will share a prefix in `u` after canonicalisation of PatKeys to `[T (T _1 _2) Int, T (T _1 _2) Bool]`. There is a one-to-many mapping between PatKeys (`_1,_2`) in `u` and the PatVar names (`a,b`, `c,d`) of the original patterns `u` represents.
Now consider a unifying lookup with the pattern `∀{e}. T e Int`. The result I'd like to see is a successful match returning `e1` with a unifier `[e :-> T a b]`. I would think that the function implementing unifying lookup can simply note this single unification constraint and pass it to a constraint solver, e.g. `solve e (T a b)`. But what type does `solve :: PatVar -> _ -> Solver -> Maybe Solver` operate on?

We could try to fill in `(BoundVarEnv, PatVarEnv, Expr)`. But where do we get the `Expr` from? We'd have to reconstruct it from the trie, which stores canonicalised PatKeys instead of Var names, so we have to come up with a mapping from PatKeys to PatVars. As we have seen, there are many such mappings (`[_1 :-> a, _2 :-> b]` and `[_1 :-> c, _2 :-> d]`), from which we'd have to reconstruct the `PatVarEnv`. Similarly for bound variables and `BoundVarEnv`. Also we'd reconstruct an `Expr` only to take it apart immediately in `solve`, what a waste of resources. Plus, it's really difficult to figure out where these mappings are stored in the trie with polymorphic recursion going on etc. Certainly we can't simply take the mappings that are stored at the end of the map entry in the `Match`, because that means we have to traverse the entire trie (i.e., not only `(T _1 _2)` but also the `Int` tail) every time we have a PatVar in the target pattern.

It would be far simpler if the constraint solver would operate on canonicalised expressions, `T _1 _2`. That's exactly `Expr'` from the OP. I think the value of being able to define unifying lookup in our paper largely outweighs the drawbacks associated with having to define such a copy of the datatype. Plus, there are ways to work around the problem:

1. Polytypic programming, for which the only viable implementation strategy so far is Template Haskell. Not an option for GHC and a heavy hammer in general, so perhaps we shouldn't stress this solution too much.
2. Trees That Grow. Make the original datatype extensible! Then we can simply add a `type Expr' = Expr Canon` where we have a constructor extension for the `BVar` and `PVar` cases from `Occ` above, remove the `Var` binder from `Lam`. Relatively simple and there is precedent in GHC. Plus, a good match for Haskell Symposium because it uses an established GHC Haskell idiom.

And just like that we have `Expr'` without the excessive maintenance burden of duplicate code.
